version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip
  - epub
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
