# Generated by Django 3.2.12 on 2022-03-25 22:46

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateRangeTest',
            fields=[
                ('id', django.contrib.postgres.fields.ranges.DateRangeField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateTest',
            fields=[
                ('id', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateTimeRangeTest',
            fields=[
                ('id', django.contrib.postgres.fields.ranges.DateTimeRangeField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateTimeTest',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerRangeTest',
            fields=[
                ('id', django.contrib.postgres.fields.ranges.IntegerRangeField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntegerTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConreteDateRangeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConreteDateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ConreteDateTimeRangeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConreteDateTimeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConreteIntegerRangeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='ConreteIntegerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', models.IntegerField()),
            ],
        ),
    ]
