# Generated by Django 3.2.13 on 2022-04-27 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DateRangeTest",
        ),
        migrations.DeleteModel(
            name="DateTest",
        ),
        migrations.DeleteModel(
            name="DateTimeRangeTest",
        ),
        migrations.DeleteModel(
            name="DateTimeTest",
        ),
        migrations.DeleteModel(
            name="DecimalRangeTest",
        ),
        migrations.DeleteModel(
            name="DecimalTest",
        ),
        migrations.DeleteModel(
            name="IntegerRangeTest",
        ),
        migrations.DeleteModel(
            name="IntegerTest",
        ),
    ]
