# Generated by Django 3.2.13 on 2022-05-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20220427_1836"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="false_field",
        ),
    ]
