# Generated by Django 5.2.11 on 2026-02-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_false_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='SimpleOrder',
        ),
    ]
