name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - run: python -m pip install black
      - run: black -l 119 --check --diff .

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - run: python -m pip install isort
      - run: isort --profile=black --line-length=119 .

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - run: python -m pip install flake8
      - run: flake8 --max-line-length=119

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: postgres
        ports: ['9932:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        include:
          # Django 2.2
          - django-version: "2.2.0"
            python-version: "3.7"
            psycopg2-version: "2.8.6"
          - django-version: "2.2.0"
            python-version: "3.8"
            psycopg2-version: "2.8.6"
          - django-version: "2.2.0"
            python-version: "3.9"
            psycopg2-version: "2.8.6"
          # Django 3.0
          - django-version: "3.0.0"
            python-version: "3.7"
            psycopg2-version: "2.8.6"
          - django-version: "3.0.0"
            python-version: "3.8"
            psycopg2-version: "2.8.6"
          - django-version: "3.0.0"
            python-version: "3.9"
            psycopg2-version: "2.8.6"
          # Django 3.1
          - django-version: "3.1.0"
            python-version: "3.7"
            psycopg2-version: "2.9.3"
          - django-version: "3.1.0"
            python-version: "3.8"
            psycopg2-version: "2.9.3"
          - django-version: "3.1.0"
            python-version: "3.9"
            psycopg2-version: "2.9.3"
          # Django 3.2
          - django-version: "3.2.0"
            python-version: "3.7"
            psycopg2-version: "2.9.3"
          - django-version: "3.2.0"
            python-version: "3.8"
            psycopg2-version: "2.9.3"
          - django-version: "3.2.0"
            python-version: "3.9"
            psycopg2-version: "2.9.3"
          - django-version: "3.2.0"
            python-version: "3.10"
            psycopg2-version: "2.9.3"
          # Django 4.0
          - django-version: "4.0.0"
            python-version: "3.8"
            psycopg2-version: "2.9.3"
          - django-version: "4.0.0"
            python-version: "3.9"
            psycopg2-version: "2.9.3"
          - django-version: "4.0.0"
            python-version: "3.10"
            psycopg2-version: "2.9.3"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r ./tests/requirements.txt

      - name: Install specific django version
        run: |
          python -m pip install "Django~=${{ matrix.django-version }}"

      - name: Install specific psycopg2 version
        # Django 2.2 & 3.0 do not like newer versions of psycopg2
        # See https://github.com/psycopg/psycopg2/issues/1293#issuecomment-862835147
        run: |
          python -m pip install "psycopg2-binary~=${{ matrix.psycopg2-version }}"

      - name: Echo Python and Django versions
        run: |
          echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
          python --version
          echo "Django: `django-admin --version`"

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Tests
        run: |
          pytest
